<h1>Error handling</h1>
<p>Error handling represents one of the most important considerations when
implementing a Node.js native add-on. When an error occurs in your C++ code you
have to handle and dispatch it correctly. <strong>node-addon-api</strong> uses return values and
JavaScript exceptions for error handling. You can choose return values or
exception handling based on the mechanism that works best for your add-on.</p>
<p>The <code>Napi::Error</code> is a persistent reference (for more info see: <a href="object_reference.md"><code>Napi::ObjectReference</code></a>)
to a JavaScript error object. Use of this class depends on whether C++
exceptions are enabled at compile time.</p>
<p>If C++ exceptions are enabled (for more info see: <a href="setup.md">Setup</a>), then the
<code>Napi::Error</code> class extends <code>std::exception</code> and enables integrated
error-handling for C++ exceptions and JavaScript exceptions.</p>
<p>The following sections explain the approach for each case:</p>
<ul>
<li><a href="#exceptions">Handling Errors With C++ Exceptions</a></li>
<li><a href="#noexceptions">Handling Errors Without C++ Exceptions</a></li>
</ul>
<p><a name="exceptions"></a></p>
<p>In most cases when an error occurs, the addon should do whatever clean is possible
and then return to JavaScript so that they error can be propagated.  In less frequent
cases the addon may be able to recover from the error, clear the error and then
continue.</p>
<h2>Handling Errors With C++ Exceptions</h2>
<p>When C++ exceptions are enabled try/catch can be used to catch exceptions thrown
from calls to JavaScript and then they can either be handled or rethrown before
returning from a native method.</p>
<p>If a node-addon-api call fails without executing any JavaScript code (for example due to
an invalid argument), then node-addon-api automatically converts and throws
the error as a C++ exception of type <code>Napi::Error</code>.</p>
<p>If a JavaScript function called by C++ code via node-addon-api throws a JavaScript
exception, then node-addon-api automatically converts and throws it as a C++
exception of type <code>Napi:Error</code> on return from the JavaScript code to the native
method.</p>
<p>If a C++ exception of type <code>Napi::Error</code> escapes from a N-API C++ callback, then
the N-API wrapper automatically converts and throws it as a JavaScript exception.</p>
<p>On return from a native method, node-addon-api will automatically convert a pending C++
exception to a JavaScript exception.</p>
<p>When C++ exceptions are enabled try/catch can be used to catch exceptions thrown
from calls to JavaScript and then they can either be handled or rethrown before
returning from a native method.</p>
<h2>Examples with C++ exceptions enabled</h2>
<h3>Throwing a C++ exception</h3>
<pre><code class="language-cpp">Env env = ...
throw Napi::Error::New(env, &quot;Example exception&quot;);
// other C++ statements
// ...
</code></pre>
<p>The statements following the throw statement will not be executed. The exception
will bubble up as a C++ exception of type <code>Napi::Error</code>, until it is either caught
while still in C++, or else automatically propagated as a JavaScript exception
when returning to JavaScript.</p>
<h3>Propagating a N-API C++ exception</h3>
<pre><code class="language-cpp">Napi::Function jsFunctionThatThrows = someObj.As&lt;Napi::Function&gt;();
Napi::Value result = jsFunctionThatThrows({ arg1, arg2 });
// other C++ statements
// ...
</code></pre>
<p>The C++ statements following the call to the JavaScript function will not be
executed. The exception will bubble up as a C++ exception of type <code>Napi::Error</code>,
until it is either caught while still in C++, or else automatically propagated as
a JavaScript exception when returning to JavaScript.</p>
<h3>Handling a N-API C++ exception</h3>
<pre><code class="language-cpp">Napi::Function jsFunctionThatThrows = someObj.As&lt;Napi::Function&gt;();
Napi::Value result;
try {
    result = jsFunctionThatThrows({ arg1, arg2 });
} catch (const Error&amp; e) {
    cerr &lt;&lt; &quot;Caught JavaScript exception: &quot; + e.what();
}
</code></pre>
<p>Since the exception was caught here, it will not be propagated as a JavaScript
exception.</p>
<p><a name="noexceptions"></a></p>
<h2>Handling Errors Without C++ Exceptions</h2>
<p>If C++ exceptions are disabled (for more info see: <a href="setup.md">Setup</a>), then the
<code>Napi::Error</code> class does not extend <code>std::exception</code>. This means that any calls to
node-addon-api function do not throw a C++ exceptions. Instead, it raises
<em>pending</em> JavaScript exceptions and returns an <em>empty</em> <code>Napi::Value</code>.
The calling code should check <code>env.IsExceptionPending()</code> before attempting to use a
returned value, and may use methods on the <code>Napi::Env</code> class
to check for, get, and clear a pending JavaScript exception (for more info see: <a href="env.md">Env</a>).
If the pending exception is not cleared, it will be thrown when the native code
returns to JavaScript.</p>
<h2>Examples with C++ exceptions disabled</h2>
<h3>Throwing a JS exception</h3>
<pre><code class="language-cpp">Napi::Env env = ...
Napi::Error::New(env, &quot;Example exception&quot;).ThrowAsJavaScriptException();
return;
</code></pre>
<p>After throwing a JavaScript exception, the code should generally return
immediately from the native callback, after performing any necessary cleanup.</p>
<h3>Propagating a N-API JS exception</h3>
<pre><code class="language-cpp">Napi::Env env = ...
Napi::Function jsFunctionThatThrows = someObj.As&lt;Napi::Function&gt;();
Napi::Value result = jsFunctionThatThrows({ arg1, arg2 });
if (env.IsExceptionPending()) {
    Error e = env.GetAndClearPendingException();
    return e.Value();
}
</code></pre>
<p>If env.IsExceptionPending() returns true a JavaScript exception is pending. To
let the exception propagate, the code should generally return immediately from
the native callback, after performing any necessary cleanup.</p>
<h3>Handling a N-API JS exception</h3>
<pre><code class="language-cpp">Napi::Env env = ...
Napi::Function jsFunctionThatThrows = someObj.As&lt;Napi::Function&gt;();
Napi::Value result = jsFunctionThatThrows({ arg1, arg2 });
if (env.IsExceptionPending()) {
    Napi::Error e = env.GetAndClearPendingException();
    cerr &lt;&lt; &quot;Caught JavaScript exception: &quot; + e.Message();
}
</code></pre>
<p>Since the exception was cleared here, it will not be propagated as a JavaScript
exception after the native callback returns.</p>
<h2>Calling N-API directly from a <strong>node-addon-api</strong> addon</h2>
<p><strong>node-addon-api</strong> provides macros for throwing errors in response to non-OK
<code>napi_status</code> results when calling <a href="https://nodejs.org/docs/latest/api/n-api.html">N-API</a>
functions from within a native addon. These macros are defined differently
depending on whether C++ exceptions are enabled or not, but are available for
use in either case.</p>
<h3><code>NAPI_THROW(e, ...)</code></h3>
<p>This macro accepts a <code>Napi::Error</code>, throws it, and returns the value given as
the last parameter. If C++ exceptions are enabled (by defining
<code>NAPI_CPP_EXCEPTIONS</code> during the build), the return value will be ignored.</p>
<h3><code>NAPI_THROW_IF_FAILED(env, status, ...)</code></h3>
<p>This macro accepts a <code>Napi::Env</code> and a <code>napi_status</code>. It constructs an error
from the <code>napi_status</code>, throws it, and returns the value given as the last
parameter. If C++ exceptions are enabled (by defining <code>NAPI_CPP_EXCEPTIONS</code>
during the build), the return value will be ignored.</p>
<h3><code>NAPI_THROW_IF_FAILED_VOID(env, status)</code></h3>
<p>This macro accepts a <code>Napi::Env</code> and a <code>napi_status</code>. It constructs an error
from the <code>napi_status</code>, throws it, and returns.</p>
<h3><code>NAPI_FATAL_IF_FAILED(status, location, message)</code></h3>
<p>This macro accepts a <code>napi_status</code>, a C string indicating the location where the
error occurred, and a second C string for the message to display.</p>
